# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 07:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_c', models.CharField(max_length=256, verbose_name='From')),
                ('where_c', models.CharField(max_length=256, verbose_name='To')),
                ('weight_c', models.IntegerField(verbose_name='Weight')),
                ('price_c', models.IntegerField(verbose_name='Price')),
                ('address_hname', models.CharField(max_length=256, verbose_name='Home Address')),
                ('address_sname', models.CharField(max_length=256, verbose_name='Street')),
                ('address_dname', models.CharField(max_length=256, verbose_name='District')),
                ('address_brname', models.CharField(max_length=256, verbose_name='Near Branch')),
                ('consignment_id', models.CharField(max_length=256)),
                ('status_n', models.BooleanField(default=False, verbose_name='Status')),
                ('date_n', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
